### ISSUE TITLE
add devsim

### ISSUE THREAD

**Issue by tcaduser** [thesourcerer8/OpenSourceTCAD#1]
Please consider adding devsim to your project.
https://github.com/devsim/devsim

It is currently built in a docker image on Travis-CI.  I would be happy to help in formulating the docker file.

**Comment by thesourcerer8** [comment]
Sure, I have been working on that already, but I couldnt get it running yet:
apt-get install liblapack-dev
sudo ln -s /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0 /usr/lib/liblapack.so.3
sudo ln -s /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 /usr/lib/libblas.so.3


git clone https://github.com/devsim/devsim
cd devsim
sh scripts/setup_ubuntu18.sh 
git submodule init
git submodule update
cd external/symdiff
sh scripts/setup_ubuntu_18.sh
cp external/SuperLU_4.3/libsuperlu.a external/SuperLU_4.3/lib/libsuperlu_4.3.a
mkdir external/getrf/build
ln -s external/getrf/libgetrf.a external/getrf/build/libgetrf.a

Add the following 2 lines to CMakeLists.txt :
include_directories(/usr/include/python3.8/)
SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC")

Remaining problem:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libsqlite3.a(sqlite3.o): relocation R_X86_64_PC32 against symbol `sqlite3_version' can not be used when making a shared object; recompile with -fPIC

Any help is highly appreciated!

**Comment by thesourcerer8** [comment]
I have pushed my latest try for a Dockerfile for DevSim now, it's not working yet, so please help to get it running!

**Comment by tcaduser** [comment]
I can take a look at it this week.  For my understanding, you want this to compile on?

- ubuntu 20.04
- using the system Python 3 interpreter, instead of Anaconda Python
- using the system blas and lapack routines, instead of Intel MKL

Most of the file locations are placed in:
```
devsim/cmake/ubuntu_16.04.cmake
```

And activated by setting:
```
DEVSIM_CONFIG="ubuntu_16.04"
```
in ``devsim/scripts/setup_ubuntu_18.04.sh``

and the build is performed in:
```
devsim/scripts/build_ubuntu.sh
```

The docker build I use on travis ci uses a Centos 6 image and is configured using these scripts:
```
devsim/scripts/build_centos_6.sh
devsim/scripts/setup_centos_6.sh
devsim/cmake/centos6.cmake
```

and the docker image is started from:
```
devsim/.travis.yml
```

The reason it is build on Centos 6 is that it is forward compatible with most modern linux distributions.  I will be migrating my travis ci build to Centos 7 in November, since Centos 6 is going to be obsolete.

**Comment by thesourcerer8** [comment]
I would like to use a as-recent-as-possible Ubuntu (perhaps a LTS version), but I could also give Centos6 a try too. I dont mind whether to use Anaconda Python or System Python, but I couldnt find anaconda packages. I dont mind Intel MKL either, but I tried now, and couldnt get the ubuntu package of MKL to install automatically, it always asks about license compatibility.

**Comment by thesourcerer8** [comment]
Thanks a lot for the help, I think we can close this issue now and open other issues for further enhancements when needed.
